import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../styles/tokens.css";
import "../styles/glass.css";
import "../styles/topnav.css";
import "./globals.css";

import { QueryProvider } from "../lib/query-client";
import VerifyEmailBanner from "../components/layout/VerifyEmailBanner";
import Header from "../components/layout/Header";
import Footer from "../components/layout/Footer";
import AuthInitializer from "../components/layout/AuthInitializer";
import { LiquidBlobBackground } from "../components/glass/LiquidBlobBackground";
import { LiquidLightLeak } from "../components/glass/LiquidLightLeak";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col bg-[#0A0C14] text-white relative">
        <QueryProvider>
          <AuthInitializer>
            <LiquidBlobBackground />
            <LiquidLightLeak />
            <VerifyEmailBanner />
            <Header />
            <main className="flex-grow z-10 relative">{children}</main>
            <Footer />
          </AuthInitializer>
        </QueryProvider>
      </body>
    </html>
  );
}

