"""add imdb and kinopoisk columns

Revision ID: 07000eff5cd1
Revises: a1b2c3d4e5f6
Create Date: 2026-07-01 12:00:36.612914

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '07000eff5cd1'
down_revision: Union[str, Sequence[str], None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('keywords',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('movie_keywords',
    sa.Column('movie_id', sa.Integer(), nullable=False),
    sa.Column('keyword_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['keyword_id'], ['keywords.id'], ),
    sa.ForeignKeyConstraint(['movie_id'], ['movies.id'], ),
    sa.PrimaryKeyConstraint('movie_id', 'keyword_id')
    )
    op.create_unique_constraint(None, 'countries', ['name'])
    op.create_unique_constraint(None, 'genres', ['name'])
    op.add_column('movies', sa.Column('imdb_id', sa.String(length=20), nullable=True))
    op.add_column('movies', sa.Column('imdb_rating', sa.Float(), nullable=True))
    op.add_column('movies', sa.Column('imdb_votes', sa.Integer(), nullable=True))
    op.add_column('movies', sa.Column('kinopoisk_id', sa.Integer(), nullable=True))
    op.add_column('movies', sa.Column('kinopoisk_rating', sa.Float(), nullable=True))
    op.add_column('movies', sa.Column('kinopoisk_votes', sa.Integer(), nullable=True))
    op.add_column('movies', sa.Column('trailer_url', sa.String(length=500), nullable=True))
    op.create_unique_constraint(None, 'movies', ['imdb_id'])
    op.create_unique_constraint(None, 'movies', ['kinopoisk_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'movies', type_='unique')
    op.drop_constraint(None, 'movies', type_='unique')
    op.drop_column('movies', 'trailer_url')
    op.drop_column('movies', 'kinopoisk_votes')
    op.drop_column('movies', 'kinopoisk_rating')
    op.drop_column('movies', 'kinopoisk_id')
    op.drop_column('movies', 'imdb_votes')
    op.drop_column('movies', 'imdb_rating')
    op.drop_column('movies', 'imdb_id')
    op.drop_constraint(None, 'genres', type_='unique')
    op.drop_constraint(None, 'countries', type_='unique')
    op.drop_table('movie_keywords')
    op.drop_table('keywords')
    # ### end Alembic commands ###
